### ISSUE TITLE
How I can add Slovenian translation (.po file)

### ISSUE THREAD

**Issue by JadranR** [WinMerge/website#15]
[sl_SI.zip](https://github.com/WinMerge/website/files/5536734/sl_SI.zip)

I send now Slovenian translation for WinMerge WebSite, per date 13.11.2020 :-)

With respect,
Jadran Rudec

**Comment by JadranR** [comment]
I send now Slovenian translation for WinMerge WebSite, per date 13.11.2020 :-)

With respect,
Jadran Rudec
### [sl_SI.zip](https://github.com/WinMerge/website/files/5541316/sl_SI.zip)

**Comment by gerundt** [comment]
Thank you, should now online: https://winmerge.org/?lang=sl

**Comment by JadranR** [comment]
Thank you !  FANTASTIC ;-)

Best Regards,
Jadran

**Comment by JadranR** [comment]
Please allow Me that I can edit this translation , or replace this string: 

msgstr ""
"<a href=\"%s\">Priročnik</a> explains how to use WinMerge, and documents its "
"capabilities and limitations."

with: msgstr ""
"<a href=\"%s\">Priročnik</a> razlaga, kako uporabljati WinMerge, ter dokumentira njegove"
"zmožnosti in omejitve"

Best Regards,
Jadran
