### ISSUE TITLE
Question regarding availability of new 2.16.17 on Website

### ISSUE THREAD

**Issue by Patriccollu** [WinMerge/website#37]
Hello,

I noticed that release 2.16.17 has been built and is now available on [WinMerge's source repository](https://github.com/WinMerge/winmerge/releases/tag/v2.16.17).

Do you know when it will be available for download on [WinMerge's Website](https://winmerge.org/downloads/)?

Thanks,
Patriccollu.

**Comment by sdottaka** [comment]
Version 2.16.17 is a beta version, not a stable version.
The next stable version, 2.16.18, will be available for download from winmerge.org when it is released.
Version 2.16.17 can be downloaded from the following URLs

https://github.com/WinMerge/winmerge/releases/tag/v2.16.17
https://sourceforge.net/projects/winmerge/files/beta/2.16.17/

**Comment by Patriccollu** [comment]
Thank you @sdottaka for clarifying. I'm closing this issue. Patriccollu.
