### ISSUE TITLE
Official documentation is outdated

### ISSUE THREAD

**Issue by ximellon** [WinMerge/website#39]
Official documentation, [here](https://manual.winmerge.org/en/), is obviously outdated since it didn't reflect the fix statements for WinMerge/winmerge#1100.

Maybe you should consider to put timestamp of generation on it so that people will know it more easily because the version number is untouched since 2019.

**Comment by sdottaka** [comment]
@gerundt Could you please update https://manual.winmerge.org/?

**Comment by gerundt** [comment]
Thanks for the hint! The online manuals should be now updated.
